/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'author' : string,
  'excerpt' : string,
  'category' : string,
}
export type Category = { 'accessories' : null } |
  { 'suspension' : null } |
  { 'brake' : null } |
  { 'electrical' : null } |
  { 'engine' : null };
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : Category,
  'rating' : number,
  'price' : number,
  'reviewCount' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBlogPostsByAuthor' : ActorMethod<[string], Array<BlogPost>>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];