/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Category = IDL.Variant({
  'accessories' : IDL.Null,
  'suspension' : IDL.Null,
  'brake' : IDL.Null,
  'electrical' : IDL.Null,
  'engine' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBlogPostsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Category = IDL.Variant({
    'accessories' : IDL.Null,
    'suspension' : IDL.Null,
    'brake' : IDL.Null,
    'electrical' : IDL.Null,
    'engine' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBlogPostsByAuthor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };